name: Workflow Test

on:
  workflow_dispatch:

jobs:
  lint-main-ui:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - name:
        run: |
          echo "test"
