name: Lint and Test

on:
  pull_request:
    paths:
      - 'ui/main-ui/**'
      - 'ui/goals/**'
      - 'ui/customer/**'

jobs:
  lint-main-ui:
    if: contains(github.event.pull_request.changed_files, 'ui/main-ui')
    runs-on: ubuntu-latest
    steps:
      - run: echo "main"

  lint-goals:
    if: contains(github.event.pull_request.changed_files, 'ui/goals')
    runs-on: ubuntu-latest
    steps:
      - run: echo "goals"

  lint-customer:
    if: contains(github.event.pull_request.changed_files, 'ui/customer')
    runs-on: ubuntu-latest
    steps:
      - run: echo "customer"
