name: Workflow Test

on:
  pull_request:
    branches: main

jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: comment
        with:
          script: |
            // Get the existing comments.
            const {data: comments} = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
            })
