name: List PR Comments

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  list-comments:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code (not strictly necessary for this task, but often included in workflows)
      - name: Checkout code
        uses: actions/checkout@v4

      # Use GitHub Script to list all comments on the PR
      - name: List all comments on the PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
            });

            // Log each comment to the output
            const botComment = comments.find(comment => comment.user.login === 2427868662)                                                                       
            console.log(botComment)
